project:
  type: website
  resources:
    - "Owen_Horton_Resume_2026.pdf"
    - "44X36_template.pdf"
    - "Text_Analysis_Project.pdf"
    - "Project_Poster.pdf"
  output-dir: docs

website:
  title: "Owen Horton"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - text: Projects
        menu:
          - href: sql.qmd
            text: SQL Project
          - href: text_analysis.qmd
            text: Text Analysis Project
          - href: terra.qmd
            text: terra Package Presentation
          - href: reportr.qmd
            text: reportr Package
          - href: poster.qmd
            text: Shiny Paper Poster
      - href: secret_hobbies.qmd
        text: Secret Hobbies

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full



