---
title: "Secret Hobbies"
---

My favorite hobby by far is Geocaching. If you haven't heard of it before, it is a worldwide "treasure hunt" game where players use a mobile app or a GPS to navigate to coordinate waypoints and find hidden containers onsite. Check out the Geocaching [homepage](https://www.geocaching.com) to see just how cool it is and start your own account! Throughout the eleven years since I started my own account, I have found more than 2,000 Geocaches worldwide, and have hidden more than 15 Geocaches in my hometown. If you go so far to look at a map of Geocaches near you, you might realize that the site is one massive geospatial database. Stay tuned for a certain Geocaching data project I plan to work on in the future!


Another major hobby of mine is solving crossword puzzles. I do the New York Times Crossword nearly every day, and while the other games they offer (Wordle, Connections, Strands, etc.) are also fun, nothing beats solving a 15x15 grid with family and friends. I highly recommend [DownForAcross](https://downforacross.org/), a user-friendly platform where crossword lovers can download, play, and collaborate on puzzles together! If crosswords are your jam too, contact me and I will be more than happy to solve one with you!
